In [133]:
import os, time, copy
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import normalize
from scipy.optimize import brentq
from scipy.stats import binom
from tqdm import tqdm

In [149]:
# Get data 2006-2014 from the following link: https://darchive.mblwhoilibrary.org/handle/1912/7341
# Unzip and merge the datasets in the following directory
calib_data = np.load('../calib-outputs.npz')
test_data = np.load('../test-outputs.npz')
calib_preds = calib_data['preds'].astype(int)
calib_labels = calib_data['labels'].astype(int)
test_preds = test_data['preds'].astype(int)
test_labels = test_data['labels'].astype(int)
classes = np.load('../classes.npy')
num_classes = classes.shape[0]

plankton_classes = np.isin(classes,['mix','mix_elongated','detritus','bad', 'bead', 'bubble', 'other_interaction', 'pollen', 'spore'],invert=True)
plankton_classes_list = np.where(plankton_classes)[0]

true_count = np.isin(test_labels, plankton_classes_list).sum()
uncorrected_est = np.isin(test_preds, plankton_classes_list).sum()
print(calib_labels.shape[0])
print(test_labels.shape[0])

421238
329832


In [150]:
# Look at the unique classes 
calib_uq, calib_uq_counts = np.unique(calib_labels, return_counts=True)
calib_uq_freq = calib_uq_counts/calib_uq_counts.sum()
calib_uq_sort = np.argsort(calib_uq_freq)[::-1]
calib_uq_freq = calib_uq_freq[calib_uq_sort]; calib_uq = calib_uq[calib_uq_sort];
calib_uq_cumsum = np.cumsum(calib_uq_freq)

In [151]:
# Problem setup
alpha = 0.1
delta_1 = 0.1-1e-2
delta_2 = 1e-2
K = 3
nu = plankton_classes.astype(int)
nu_trunc = nu[calib_uq]
calib_uq = calib_uq[:K]

In [152]:
# Construct the confusion matrix
n = calib_preds.shape[0]
N = test_preds.shape[0]

idx_calib_preds_excluded = np.logical_not(np.isin(calib_preds,calib_uq))
calib_preds[idx_calib_preds_excluded] = np.random.choice(calib_uq,size=(idx_calib_preds_excluded.sum(),), replace=True,p=calib_uq_freq[:K]/calib_uq_freq[:K].sum())
idx_test_preds_excluded = np.logical_not(np.isin(test_preds,calib_uq))
test_preds[idx_test_preds_excluded] = np.random.choice(calib_uq, size=(idx_test_preds_excluded.sum(),), replace=True,p=calib_uq_freq[:K]/calib_uq_freq[:K].sum())

C = np.zeros((num_classes,num_classes)).astype(int)
for j in range(num_classes):
    for l in range(num_classes):
        C[j,l] = ((calib_preds == j) & (calib_labels == l)).sum()

In [153]:
# Construct Ahat
Ahat = C[:,calib_uq][calib_uq,:]
Ahat = Ahat / (Ahat.sum(axis=1)[:,None])
Ahatinv = np.linalg.inv(Ahat)
print(np.array_str(Ahat, precision=3))
print(np.array_str(Ahatinv, precision=3))

[[0.941 0.052 0.007]
 [0.069 0.916 0.015]
 [0.03  0.046 0.924]]
[[ 1.068 -0.061 -0.007]
 [-0.08   1.097 -0.017]
 [-0.031 -0.052  1.083]]


In [154]:
# Construct the point estimate
target_uq, target_uq_counts = np.unique(test_preds, return_counts=True)
target_uq_freq = target_uq_counts/target_uq_counts.sum()
target_uq_sort = np.argsort(target_uq_freq)[::-1]
target_uq_freq = target_uq_freq[target_uq_sort]; target_uq = target_uq[target_uq_sort];
target_uq = target_uq[:K]
qfhat = target_uq_freq[:K]
nu1 = nu_trunc[:K]
nu2 = nu_trunc[K:]

In [157]:
print(1-(np.linalg.pinv(Ahat[:,:-1])@qfhat).sum())
print(nu1@Ahatinv@qfhat)

0.02919551399867626
-0.010469174659525422


In [156]:
# Run MAI
nmin = int(calib_uq_freq[:K].min()*n)
point_estimate = nu1@np.maximum(Ahatinv@qfhat,0)
term1 = np.abs(nu1@Ahatinv).sum()*np.sqrt(2/nmin*np.log(2*(K+1)/delta_1))
term2 = np.abs(nu1@Ahatinv).sum()*np.sqrt(2/N*np.log(2*(K+1)/delta_1))
term3_ub = nu1.max()*alpha
term3_lb = nu1.min()*alpha
print(point_estimate)

qyhat_ub = np.minimum(point_estimate + term1 + term2 + term3_ub,1)
qyhat_lb = np.maximum(point_estimate - term1 - term2 - term3_lb,0)

count_plankton_lb = int(binom.ppf(delta_2, N, qyhat_lb))
count_plankton_ub = int(binom.ppf(1-delta_2, N, qyhat_ub))

0.0


In [142]:
print(f"The model-assisted confidence interval for the number of plankton observed in 2014 is [{count_plankton_lb},{count_plankton_ub}] ([{100*qyhat_lb:.1f}%,{100*qyhat_ub:.1f}%]).")
print(f"The true number of plankton observed in 2014 was {true_count} ({true_count/N*100:.1f}%), which lies in the interval.")
print(f"The uncorrected estimate was {uncorrected_est} ({uncorrected_est/N*100:.1f}%).")

The model-assisted confidence interval for the number of plankton observed in 2014 is [297570,329832] ([90.3%,100.0%]).
The true number of plankton observed in 2014 was 23538 (7.1%), which lies in the interval.
The uncorrected estimate was 16975 (5.1%).
